services:
  db:
    build:
      dockerfile: docker/db.Dockerfile
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
      - .:/workspace
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DUMPFILE=/workspace/purple.dump

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
    ports:
      - "8888:8000"
    environment:
      - PURPLE_DEPLOYMENT_MODE=development
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - PURPLE_RPC_API_TOKEN=devtoken
      # OIDC RP client credential for dev instance of datatracker (not secret for dev, will be for production)
      - PURPLE_OIDC_RP_CLIENT_ID=502412
      - PURPLE_OIDC_RP_CLIENT_SECRET=4046925638956f0d733cd96a5a89646815f0e989c878e9e09475b2f8
      - NUXT_PUBLIC_DATATRACKER_BASE=http://localhost:8000
    depends_on:
      - db
      - mq
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery:
    image: "${COMPOSE_PROJECT_NAME}-app"
    command: [ "/celery-init.sh" ]  # without beat
    # command: [ "/celery-init.sh", "-BE" ]  # with beat
    volumes:
      - .:/workspace
    restart: unless-stopped
    environment:
      - PURPLE_DEPLOYMENT_MODE=development
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - PURPLE_RPC_API_TOKEN=devtoken
      # OIDC RP client credential for dev instance of datatracker (not secret for dev, will be for production)
      - PURPLE_OIDC_RP_CLIENT_ID=502412
      - PURPLE_OIDC_RP_CLIENT_SECRET=4046925638956f0d733cd96a5a89646815f0e989c878e9e09475b2f8
      - NUXT_PUBLIC_DATATRACKER_BASE=http://localhost:8000
    depends_on:
      - db
      - mq
      - memcache
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mailpit:
    image: axllent/mailpit:v1.27
    environment:
      - MP_DISABLE_VERSION_CHECK=true
      - MP_LABEL=PurpleMail
    ports:
      - "1025:1025"
      - "8025:8025"

  memcache:
    image: memcached:latest
    restart: unless-stopped
    command:
      - --memory-limit=128

  mq:
    image: rabbitmq:4.1-management

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
        - PGADMIN_DEFAULT_EMAIL=dev@ietf.org
        - PGADMIN_DEFAULT_PASSWORD=dev
        - PGADMIN_CONFIG_LOGIN_BANNER="Login with dev@ietf.org / dev"
        - PGADMIN_DISABLE_POSTFIX=True
        - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
        - SCRIPT_NAME=/pgadmin
    volumes:
        - ./docker/configs/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgresdb-data:
